//Ricardo Lima 2565510
//Geisily Varga 2478404;
//Raí I. Morato 2623420;

package br.com.banco.visao;

import br.com.banco.controle.GerenciadorDeContas;
import br.com.banco.modelo.ContaBancaria;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author Ricardo
 * SRP: Responsabilidade única - Interface de entrada de conta
 */
public class FormEntrarConta extends javax.swing.JFrame {

    ContaBancaria contaBancaria;
    // SRP: Constantes para mensagens e títulos, facilitando manutenção
    private static final String TITULO_ERRO = "Erro";
    private static final String TITULO_CONFIRMACAO = "Confirmação de Saída";
    private static final String MENSAGEM_CAMPOS_VAZIOS = "Por favor, informe o número da conta e a agência.";
    private static final String MENSAGEM_CONTA_INCORRETA = "Conta ou agência incorretos.";
    private static final String MENSAGEM_SAIR = "Deseja realmente sair?";
    
    /**
     * Creates new form FormExibirConta
     * SRP: Construtor apenas inicializa a interface
     */
    public FormEntrarConta() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtAgencia = new javax.swing.JLabel();
        cxAgencia = new javax.swing.JTextField();
        rtNumeroConta = new javax.swing.JLabel();
        cxNumeroConta = new javax.swing.JTextField();
        btEntrar = new javax.swing.JButton();
        btCriarConta = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtAgencia.setText("Agência");

        rtNumeroConta.setText("Número da Conta");

        cxNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaActionPerformed(evt);
            }
        });

        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        btCriarConta.setText("Criar Conta");
        btCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarContaActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setText("ACESSE SUA CONTA");

        btRelatorio.setText("Relatório");
        btRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btEntrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSair))
                            .addComponent(rtAgencia)
                            .addComponent(cxAgencia)
                            .addComponent(cxNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(rtNumeroConta)))
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(140, 140, 140))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCriarConta)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rtNumeroConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(rtAgencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntrar)
                    .addComponent(btSair))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCriarConta)
                    .addComponent(btRelatorio))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarContaActionPerformed
        abreCriarConta();
    }//GEN-LAST:event_btCriarContaActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void cxNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumeroContaActionPerformed
    
    public void abreCriarConta(){
        FormCadConta telaConta = new FormCadConta();
        telaConta.setVisible(true);
    }
    
    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        // Boa Prática 2: Validação de entrada com método separado para melhor legibilidade
        if (!validarCampos()) {
            return;
        }

        String numeroConta = cxNumeroConta.getText().trim();
        String agencia = cxAgencia.getText().trim();

        ContaBancaria conta = GerenciadorDeContas.buscarConta(numeroConta, agencia);

        if (conta != null) {
            abreConta(conta);
        } else {
            JOptionPane.showMessageDialog(this, MENSAGEM_CONTA_INCORRETA, TITULO_ERRO, JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }//GEN-LAST:event_btEntrarActionPerformed

    private void btRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioActionPerformed
        abreRelatorio();
    }//GEN-LAST:event_btRelatorioActionPerformed

    public void abreConta(ContaBancaria conta){
        FormConta telaConta = new FormConta(conta);
        telaConta.setVisible(true);
    }
    
    public void abreRelatorio(){
        FormRelContas telaRelatorio = new FormRelContas();
        telaRelatorio.setVisible(true);
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            null,
            MENSAGEM_SAIR,
            TITULO_CONFIRMACAO,
            JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            //System.exit(0);
            dispose();
        }
    }
    
    /**
     * Valida se os campos obrigatórios foram preenchidos
     * @return true se os campos estão válidos, false caso contrário
     */
    private boolean validarCampos() {
        String numeroConta = cxNumeroConta.getText().trim();
        String agencia = cxAgencia.getText().trim();

        if (numeroConta.isEmpty() || agencia.isEmpty()) {
            JOptionPane.showMessageDialog(this, MENSAGEM_CAMPOS_VAZIOS, TITULO_ERRO, JOptionPane.ERROR_MESSAGE);
            cxNumeroConta.requestFocus();
            return false;
        }
        return true;
    }
    
    public void limpar() {
        cxNumeroConta.setText("");
        cxAgencia.setText("");
        cxNumeroConta.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEntrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEntrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEntrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEntrarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEntrarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriarConta;
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btRelatorio;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAgencia;
    private javax.swing.JTextField cxNumeroConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rtAgencia;
    private javax.swing.JLabel rtNumeroConta;
    // End of variables declaration//GEN-END:variables
}
