//Ricardo Lima 2565510
//Geisily Varga 2478404;
//Raí I. Morato 2623420;

package br.com.banco.visao;
import javax.swing.JOptionPane;

import br.com.banco.controle.GerenciadorDeContas;
import br.com.banco.modelo.ContaBancaria;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ricardo
 */
public class FormSacar extends javax.swing.JFrame {

    private FormConta telaPrincipal;
    
    /**
     * Creates new form FormSacar
     */
    public FormSacar() {
        initComponents();
    }
    
    public FormSacar(FormConta telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        initComponents();
        preencherDadosConta();
    }
    
    private void preencherDadosConta() {
        if (telaPrincipal != null && telaPrincipal.getConta() != null) {
            ContaBancaria conta = telaPrincipal.getConta();
            cxNumeroConta.setText(conta.getNumeroConta());
            cxAgencia.setText(conta.getAgencia());
            cxNumeroConta.setEnabled(false); // Desabilita edição
            cxAgencia.setEnabled(false); // Desabilita edição
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtSacar = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        rtNumeroConta = new javax.swing.JLabel();
        cxNumeroConta = new javax.swing.JTextField();
        rtValorSaque = new javax.swing.JLabel();
        cxValorSaque = new javax.swing.JTextField();
        btSacar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        rtAgencia = new javax.swing.JLabel();
        cxAgencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtSacar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtSacar.setText("Sacar");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtNumeroConta.setText("Número da conta");

        cxNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNumeroContaActionPerformed(evt);
            }
        });

        rtValorSaque.setText("Valor para saque");

        btSacar.setText("Sacar");
        btSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSacarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        rtAgencia.setText("Agência");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxAgencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rtAgencia)
                        .addGap(37, 37, 37)))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSacar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLimpar))
                    .addComponent(cxValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(rtValorSaque)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rtSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSair)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(rtSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtAgencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtNumeroConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(rtValorSaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSacar)
                    .addComponent(btLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btSair)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNumeroContaActionPerformed

    
    private void btSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSacarActionPerformed
        String numeroConta = cxNumeroConta.getText().trim();
        String agencia = cxAgencia.getText().trim();
        String valorStr = cxValorSaque.getText().trim();

        if (numeroConta.isEmpty() || agencia.isEmpty() || valorStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double valorSaque = Double.parseDouble(valorStr);
            if (valorSaque <= 0) {
                JOptionPane.showMessageDialog(this, "O valor do saque deve ser maior que zero.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verificar se a conta existe
            ContaBancaria conta = GerenciadorDeContas.buscarConta(numeroConta, agencia);
            if (conta == null) {
                JOptionPane.showMessageDialog(this, "Conta não encontrada. Verifique o número da conta e agência.", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Verificar se há saldo suficiente
            if (!GerenciadorDeContas.temSaldoSuficiente(numeroConta, agencia, valorSaque)) {
                JOptionPane.showMessageDialog(this, 
                    "Saldo insuficiente. Saldo atual: R$ " + String.format("%.2f", conta.getSaldo()), 
                    "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean sucesso = GerenciadorDeContas.sacar(numeroConta, agencia, valorSaque);
                
            if (sucesso) {
                // Atualizar a tela principal
                if (telaPrincipal != null) {
                    telaPrincipal.atualizarSaldo();
                }
                
                JOptionPane.showMessageDialog(this, 
                    "Saque realizado com sucesso!\nValor sacado: R$ " + String.format("%.2f", valorSaque) + 
                    "\nSaldo restante: R$ " + String.format("%.2f", conta.getSaldo() - valorSaque), 
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                dispose(); // Fecha o formulário após o saque
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao realizar o saque. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite um valor válido para saque.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        limpar();
    }//GEN-LAST:event_btSacarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Confirmação de Saída",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            //System.exit(0);
            dispose();
        }
    }
    
    public void limpar(){
        cxNumeroConta.setText("");
        cxAgencia.setText("");
        cxValorSaque.setText("");
        cxNumeroConta.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSacar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAgencia;
    private javax.swing.JTextField cxNumeroConta;
    private javax.swing.JTextField cxValorSaque;
    private javax.swing.JLabel rtAgencia;
    private javax.swing.JLabel rtNumeroConta;
    private javax.swing.JLabel rtSacar;
    private javax.swing.JLabel rtValorSaque;
    // End of variables declaration//GEN-END:variables
}
