//Ricardo Lima 2565510
//Geisily Varga 2478404;
//Raí I. Morato;

package br.visao;

import br.com.banco.modelo.ContaBancaria;
import br.com.banco.controle.GerenciadorDeContas;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ricardo
 */
public class FormConta extends javax.swing.JFrame {
    
    /**
     * Creates new form FormExibirSaldo
     */
    
    private ContaBancaria conta;
    
    public FormConta(ContaBancaria conta) {
        this.conta = conta;
        initComponents();
        preencherDados();
        verificarTipoConta();
    }
    
    private void preencherDados() {
        if (conta != null) {
            cxNumeroConta.setText(conta.getNumeroConta());
            cxAgencia.setText(conta.getAgencia());
            cxSaldo.setText("R$ " + String.format("%.2f", conta.getSaldo()));
            cxTitular.setText(conta.getTitular());
            cxTipoConta.setText(conta.getTipoConta());
        }
    }

    private void verificarTipoConta() {
        if (conta != null && "Salário".equalsIgnoreCase(conta.getTipoConta())) {
            btPix.setEnabled(false);
        }
    }
    
    // Método para atualizar o saldo da conta em tempo real
    public void atualizarSaldo() {
        if (conta != null) {
            // Buscar a conta atualizada no banco de dados
            ContaBancaria contaAtualizada = GerenciadorDeContas.buscarConta(conta.getNumeroConta(), conta.getAgencia());
            if (contaAtualizada != null) {
                this.conta = contaAtualizada;
                cxSaldo.setText("R$ " + String.format("%.2f", conta.getSaldo()));
                System.out.println("Saldo atualizado: R$ " + String.format("%.2f", conta.getSaldo()));
            }
        }
    }
    
    // Getter para a conta atual
    public ContaBancaria getConta() {
        return conta;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtNumeroConta = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        rtAgencia = new javax.swing.JLabel();
        rtSaldo = new javax.swing.JLabel();
        rtTitular = new javax.swing.JLabel();
        rtTipoConta = new javax.swing.JLabel();
        btDepositar = new javax.swing.JButton();
        btSacar = new javax.swing.JButton();
        btPix = new javax.swing.JButton();
        cxTipoConta = new javax.swing.JLabel();
        cxAgencia = new javax.swing.JLabel();
        cxTitular = new javax.swing.JLabel();
        cxNumeroConta = new javax.swing.JLabel();
        cxSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtNumeroConta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtNumeroConta.setText("Número da conta");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtAgencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtAgencia.setText("Agência");

        rtSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtSaldo.setText("Saldo Disponível");

        rtTitular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTitular.setText("Titular");

        rtTipoConta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtTipoConta.setText("Tipo de Conta");

        btDepositar.setText("Depositar");
        btDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositarActionPerformed(evt);
            }
        });

        btSacar.setText("Sacar");
        btSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSacarActionPerformed(evt);
            }
        });

        btPix.setText("Transferir Via PIX");
        btPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPixActionPerformed(evt);
            }
        });

        cxTipoConta.setText("Tipo");

        cxAgencia.setText("Agencia");

        cxTitular.setText("Nome");

        cxNumeroConta.setText("Conta");

        cxSaldo.setText("R$ 0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btSair)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rtTitular, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rtTipoConta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cxTipoConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cxTitular, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rtNumeroConta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rtAgencia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cxAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cxNumeroConta, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rtSaldo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btDepositar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btPix)))
                                .addGap(18, 18, 18)
                                .addComponent(btSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(cxSaldo)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTitular)
                    .addComponent(rtNumeroConta))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNumeroConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cxTitular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rtTipoConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxTipoConta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rtAgencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxAgencia)))
                .addGap(18, 18, 18)
                .addComponent(rtSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDepositar)
                    .addComponent(btPix)
                    .addComponent(btSacar))
                .addGap(35, 35, 35)
                .addComponent(btSair)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositarActionPerformed
        abreDeposito();
    }//GEN-LAST:event_btDepositarActionPerformed

    private void btPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPixActionPerformed
        abrePix();
    }//GEN-LAST:event_btPixActionPerformed

    private void btSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSacarActionPerformed
        abreSacar();
    }//GEN-LAST:event_btSacarActionPerformed
   
    public void abreSacar(){
        FormSacar telaSacar = new FormSacar(this);
        telaSacar.setVisible(true);
    }
    
    public void abrePix(){
        FormPix formPix = new FormPix(this);
        formPix.setVisible(true);
    }
    
    public void abreDeposito(){
        FormDeposito telaDeposito = new FormDeposito(this);
        telaDeposito.setVisible(true);
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Confirmação de Saída",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            //System.exit(0);
            dispose();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConta(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDepositar;
    private javax.swing.JButton btPix;
    private javax.swing.JButton btSacar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel cxAgencia;
    private javax.swing.JLabel cxNumeroConta;
    private javax.swing.JLabel cxSaldo;
    private javax.swing.JLabel cxTipoConta;
    private javax.swing.JLabel cxTitular;
    private javax.swing.JLabel rtAgencia;
    private javax.swing.JLabel rtNumeroConta;
    private javax.swing.JLabel rtSaldo;
    private javax.swing.JLabel rtTipoConta;
    private javax.swing.JLabel rtTitular;
    // End of variables declaration//GEN-END:variables
}
